baseURL: https://aidenwebb.github.io
languageCode: en-gb
title: Aiden Arnkels-Webb
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  homeInfoParams:
      Title: Hi there!
      Content: Here you can find my general ramblings, fun projects, technical guides and other stuff
  socialIcons: # optional
      - name: "<platform>"
        url: "<link>"
      - name: "<platform 2>"
        url: "<link2>"
  DateFormat: "January 2, 2006"
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false