baseURL: https://aidenwebb.com
languageCode: en-gb
title: Aiden Arnkels-Webb
theme: PaperMod
copyright: "@ Aiden Arnkels-Webb"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-153771324-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Aiden Arnkels-Webb | Systems Architect
  description: "Here you can find my general ramblings, fun projects, technical guides and other stuff"
  keywords: [Blog, Portfolio]
  author: Aiden Arnkels-Webb
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light 
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B I'm Aiden"
    Content: Welcome to my blog! I'm a Systems and Infrastructure Architect based in Bournemouth, UK. Here you can find my general ramblings, fun projects, technical guides among other things. You can reach me at `hello [at] aidenwebb.com`

  socialIcons:
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4121552/aidenwebb"
    - name: github
      url: "https://github.com/Aidenwebb"
    - name: linkedin
      url: https://www.linkedin.com/in/aiden-arnkels-webb/

  analytics:
    #google:
      #SiteVerificationTag: "XYZabc"
    #bing:
      #SiteVerificationTag: "XYZabc"
    #yandex:
      #SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/Aidenwebb/aidenwebb.github.io/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about me
      url: /about/
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: true
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
permalinks:
  posts: /posts/:title/

disqusShortname: aidenwebb